// Reddit subreddit mapping for NBA teams
export const teamSubreddits: Record<string, string> = {
  Hawks: "AtlantaHawks",
  Celtics: "bostonceltics",
  Nets: "GoNets",
  Hornets: "CharlotteHornets",
  Bulls: "chicagobulls",
  Cavaliers: "clevelandcavs",
  Mavericks: "Mavericks",
  Nuggets: "denvernuggets",
  Pistons: "DetroitPistons",
  Warriors: "warriors",
  Rockets: "rockets",
  Pacers: "pacers",
  Clippers: "LAClippers",
  Lakers: "lakers",
  Grizzlies: "memphisgrizzlies",
  Heat: "heat",
  Bucks: "MkeBucks",
  Timberwolves: "timberwolves",
  Pelicans: "NOLAPelicans",
  Knicks: "NYKnicks",
  Thunder: "Thunder",
  Magic: "OrlandoMagic",
  "76ers": "sixers",
  Suns: "suns",
  "Trail Blazers": "ripcity",
  Kings: "kings",
  Spurs: "NBASpurs",
  Raptors: "torontoraptors",
  Jazz: "UtahJazz",
  Wizards: "washingtonwizards",
};
